@startuml

title __EXTENSIBLE-BOWLING-GAME's Class Diagram__\n

  namespace  {
    class AddPartyView {
    }
  }
  

  namespace  {
    class AdhocView {
    }
  }
  

  namespace  {
    class Alley {
    }
  }
  

  namespace  {
    class Bowler {
    }
  }
  

  namespace  {
    class BowlerFile {
    }
  }
  

  namespace  {
    class BowlerScoreView {
    }
  }
  

  namespace  {
    class BowlerScorer {
    }
  }
  

  namespace  {
    class BowlerScorerTest {
    }
  }
  

  namespace  {
    class ControlDesk {
    }
  }
  

  namespace  {
    class ControlDeskEvent {
    }
  }
  

  namespace  {
    class ControlDeskView {
    }
  }
  

  namespace  {
    class EndGamePrompt {
    }
  }
  

  namespace  {
    class EndGameReport {
    }
  }
  

  namespace  {
    interface Event {
    }
  }
  

  namespace  {
    interface GeneralBowler {
    }
  }
  

  namespace  {
    interface GeneralParty {
    }
  }
  

  namespace  {
    interface GeneralPinsetter {
    }
  }
  

  namespace  {
    class Lane {
    }
  }
  

  namespace  {
    class LaneEvent {
    }
  }
  

  namespace  {
    interface LaneInterface {
    }
  }
  

  namespace  {
    class LaneScorer {
    }
  }
  

  namespace  {
    class LaneStatusView {
    }
  }
  

  namespace  {
    class LaneView {
    }
  }
  

  namespace  {
    class NewPatronView {
    }
  }
  

  namespace  {
    interface Observer {
    }
  }
  

  namespace  {
    class Party {
    }
  }
  

  namespace  {
    class PinSetterView {
    }
  }
  

  namespace  {
    class Pinsetter {
    }
  }
  

  namespace  {
    class PinsetterEvent {
    }
  }
  

  namespace  {
    class PrintableText {
    }
  }
  

  namespace  {
    abstract class Publisher {
    }
  }
  

  namespace  {
    class Queue {
    }
  }
  

  namespace  {
    class Score {
    }
  }
  

  namespace  {
    class ScoreHistoryFile {
    }
  }
  

  namespace  {
    class ScoreReport {
    }
  }
  

  namespace  {
    class Util {
    }
  }
  

  namespace  {
    namespace idget {
      class Widget.ButtonPanel {
      }
    }
  }
  

  namespace  {
    namespace idget {
      class Widget.ContainerPanel {
      }
    }
  }
  

  namespace  {
    namespace idget {
      abstract class Widget.FormPanel {
      }
    }
  }
  

  namespace  {
    namespace idget {
      abstract class Widget.GenericPanel {
      }
    }
  }
  

  namespace  {
    namespace idget {
      class Widget.GridPanel {
      }
    }
  }
  

  namespace  {
    namespace idget {
      class Widget.ScrollablePanel {
      }
    }
  }
  

  namespace  {
    namespace idget {
      class Widget.TextFieldPanel {
      }
    }
  }
  

  namespace  {
    namespace idget {
      class Widget.WindowFrame {
      }
    }
  }
  

  namespace  {
    class drive {
    }
  }
  

  AddPartyView .up.|> ActionListener
  AddPartyView .up.|> ListSelectionListener
  AdhocView .up.|> ActionListener
  Bowler .up.|> GeneralBowler
  ControlDesk .up.|> Runnable
  ControlDeskEvent .up.|> Event
  ControlDeskView .up.|> ActionListener
  ControlDeskView .up.|> Observer
  EndGamePrompt .up.|> ActionListener
  EndGameReport .up.|> ActionListener
  EndGameReport .up.|> ListSelectionListener
  Lane .up.|> LaneInterface
  Lane .up.|> Observer
  Lane .up.|> Runnable
  LaneEvent .up.|> Event
  LaneStatusView .up.|> ActionListener
  LaneStatusView .up.|> Observer
  LaneView .up.|> ActionListener
  LaneView .up.|> Observer
  NewPatronView .up.|> ActionListener
  Party .up.|> GeneralParty
  PinSetterView .up.|> Observer
  Pinsetter .up.|> GeneralPinsetter
  PinsetterEvent .up.|> Event
  PrintableText .up.|> Printable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
