@startuml

title __EXTENSIBLE-BOWLING-GAME's Class Diagram__\n

  namespace  {
    class AddPartyView {
    }
  }
  

  namespace  {
    class AdhocView {
    }
  }
  

  namespace  {
    class Alley {
    }
  }
  

  namespace  {
    class Bowler {
    }
  }
  

  namespace  {
    class BowlerFile {
    }
  }
  

  namespace  {
    class BowlerScoreView {
    }
  }
  

  namespace  {
    class BowlerScorerTest {
    }
  }
  

  namespace  {
    class BowlingAlleyDriver {
    }
  }
  

  namespace  {
    class ControlDesk {
    }
  }
  

  namespace  {
    class ControlDeskEvent {
    }
  }
  

  namespace  {
    class ControlDeskView {
    }
  }
  

  namespace  {
    class EndGamePrompt {
    }
  }
  

  namespace  {
    class EndGameReport {
    }
  }
  

  namespace  {
    interface Event {
    }
  }
  

  namespace  {
    class Frame {
    }
  }
  

  namespace  {
    class Lane {
    }
  }
  

  namespace  {
    class LaneEvent {
    }
  }
  

  namespace  {
    interface LaneInterface {
    }
  }
  

  namespace  {
    class LaneStatusView {
    }
  }
  

  namespace  {
    class LaneView {
    }
  }
  

  namespace  {
    class LastFrame {
    }
  }
  

  namespace  {
    class NewPatronView {
    }
  }
  

  namespace  {
    interface Observer {
    }
  }
  

  namespace  {
    class Party {
    }
  }
  

  namespace  {
    class PinSetterView {
    }
  }
  

  namespace  {
    class Pinsetter {
    }
  }
  

  namespace  {
    class PinsetterEvent {
    }
  }
  

  namespace  {
    class PrintableText {
    }
  }
  

  namespace  {
    abstract class Publisher {
    }
  }
  

  namespace  {
    class ScorableBowler {
    }
  }
  

  namespace  {
    class ScorableParty {
    }
  }
  

  namespace  {
    class Score {
    }
  }
  

  namespace  {
    class ScoreHistoryFile {
    }
  }
  

  namespace  {
    class ScoreReport {
    }
  }
  

  namespace  {
    class Util {
    }
  }
  

  namespace  {
    namespace idget {
      class Widget.ButtonPanel {
      }
    }
  }
  

  namespace  {
    namespace idget {
      class Widget.ContainerPanel {
      }
    }
  }
  

  namespace  {
    namespace idget {
      abstract class Widget.FormPanel {
      }
    }
  }
  

  namespace  {
    namespace idget {
      abstract class Widget.GenericPanel {
      }
    }
  }
  

  namespace  {
    namespace idget {
      class Widget.GridPanel {
      }
    }
  }
  

  namespace  {
    namespace idget {
      class Widget.ScrollablePanel {
      }
    }
  }
  

  namespace  {
    namespace idget {
      class Widget.TextFieldPanel {
      }
    }
  }
  

  namespace  {
    namespace idget {
      class Widget.WindowFrame {
      }
    }
  }
  

  AddPartyView .up.|> java.awt.event.ActionListener
  AddPartyView .up.|> javax.swing.event.ListSelectionListener
  AddPartyView o-- Widget.ButtonPanel : buttonPanel
  AddPartyView o-- ControlDeskView : controlDesk
  AddPartyView o-- Widget.WindowFrame : win
  AdhocView .up.|> java.awt.event.ActionListener
  AdhocView o-- Widget.ButtonPanel : buttonPanel
  AdhocView o-- Score : currScore
  AdhocView o-- Widget.ContainerPanel : statDisplay
  AdhocView o-- Widget.WindowFrame : win
  BowlerScoreView o-- Widget.GridPanel : gridPanel
  ControlDesk .up.|> java.lang.Runnable
  ControlDesk -up-|> Publisher
  ControlDeskEvent .up.|> Event
  ControlDeskView .up.|> Observer
  ControlDeskView .up.|> java.awt.event.ActionListener
  ControlDeskView o-- ControlDesk : controlDesk
  ControlDeskView o-- Widget.ButtonPanel : controlsPanel
  ControlDeskView o-- Widget.WindowFrame : win
  EndGamePrompt .up.|> java.awt.event.ActionListener
  EndGamePrompt o-- Widget.ButtonPanel : buttonPanel
  EndGamePrompt o-- Widget.WindowFrame : win
  EndGameReport .up.|> java.awt.event.ActionListener
  EndGameReport .up.|> javax.swing.event.ListSelectionListener
  EndGameReport o-- Widget.ButtonPanel : buttonPanel
  EndGameReport o-- Widget.WindowFrame : win
  Lane .up.|> LaneInterface
  Lane .up.|> Observer
  Lane .up.|> java.lang.Runnable
  Lane -up-|> Publisher
  Lane o-- Pinsetter : pinsetter
  Lane o-- ScorableParty : scorer
  LaneEvent .up.|> Event
  LaneStatusView .up.|> Observer
  LaneStatusView .up.|> java.awt.event.ActionListener
  LaneStatusView o-- Widget.ButtonPanel : buttonPanel
  LaneStatusView o-- Widget.ContainerPanel : gamePanel
  LaneStatusView o-- Lane : lane
  LaneStatusView o-- LaneView : laneView
  LaneStatusView o-- PinSetterView : pinSetterView
  LaneView .up.|> Observer
  LaneView .up.|> java.awt.event.ActionListener
  LaneView o-- Widget.ButtonPanel : buttonPanel
  LaneView o-- Widget.ContainerPanel : containerPanel
  LaneView o-- LaneInterface : lane
  LastFrame -up-|> Frame
  NewPatronView .up.|> java.awt.event.ActionListener
  NewPatronView o-- AddPartyView : addParty
  NewPatronView o-- Widget.ButtonPanel : buttonPanel
  NewPatronView o-- Widget.TextFieldPanel : patronPanel
  NewPatronView o-- Widget.WindowFrame : window
  PinSetterView .up.|> Observer
  Pinsetter -up-|> Publisher
  PinsetterEvent .up.|> Event
  PrintableText .up.|> java.awt.print.Printable
  ScorableBowler -up-|> Bowler
  ScorableParty -up-|> Party
  Widget.ButtonPanel -up-|> Widget.FormPanel
  Widget.ContainerPanel -up-|> Widget.GenericPanel
  Widget.FormPanel -up-|> Widget.GenericPanel
  Widget.GridPanel -up-|> Widget.GenericPanel
  Widget.ScrollablePanel -up-|> Widget.GenericPanel
  Widget.TextFieldPanel -up-|> Widget.FormPanel


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
