@startuml

title __EXTENSIBLE-BOWLING-GAME's Class Diagram__\n

  namespace BowlingGame {
    class ControlDesk.AddPartyView {
    }
  }
  

  namespace BowlingGame {
    class ControlDesk.AdhocView {
    }
  }
  

  namespace BowlingGame {
    class Alley {
    }
  }
  

  namespace BowlingGame {
    class Bowlers.Bowler {
    }
  }
  

  namespace BowlingGame {
    class Utilities.BowlerFile {
    }
  }
  

  namespace BowlingGame {
    class Bowlers.BowlerScoreView {
    }
  }
  

  namespace BowlingGame {
    class Bowlers.BowlerScorerTest {
    }
  }
  

  namespace BowlingGame {
    class BowlingAlleyDriver {
    }
  }
  

  namespace BowlingGame {
    class ControlDesk.ControlDesk {
    }
  }
  

  namespace BowlingGame {
    class Observer.ControlDeskEvent {
    }
  }
  

  namespace BowlingGame {
    class ControlDesk.ControlDeskView {
    }
  }
  

  namespace BowlingGame {
    class Endgame.EndGamePrompt {
    }
  }
  

  namespace BowlingGame {
    class Endgame.EndGameReport {
    }
  }
  

  namespace BowlingGame {
    interface Observer.Event {
    }
  }
  

  namespace BowlingGame {
    class Bowlers.Frame {
    }
  }
  

  namespace BowlingGame {
    class Lane.Lane {
    }
  }
  

  namespace BowlingGame {
    class Observer.LaneEvent {
    }
  }
  

  namespace BowlingGame {
    interface LaneInterface {
    }
  }
  

  namespace BowlingGame {
    class Lane.LaneStatusView {
    }
  }
  

  namespace BowlingGame {
    class Lane.LaneView {
    }
  }
  

  namespace BowlingGame {
    class Bowlers.LastFrame {
    }
  }
  

  namespace BowlingGame {
    class ControlDesk.NewPatronView {
    }
  }
  

  namespace BowlingGame {
    interface Observer.Observer {
    }
  }
  

  namespace BowlingGame {
    class Bowlers.Party {
    }
  }
  

  namespace BowlingGame {
    class Pinsetter.PinSetterView {
    }
  }
  

  namespace BowlingGame {
    class Pinsetter.Pinsetter {
    }
  }
  

  namespace BowlingGame {
    class Observer.PinsetterEvent {
    }
  }
  

  namespace BowlingGame {
    class Utilities.PrintableText {
    }
  }
  

  namespace BowlingGame {
    abstract class Observer.Publisher {
    }
  }
  

  namespace BowlingGame {
    class Bowlers.ScorableBowler {
    }
  }
  

  namespace BowlingGame {
    class Bowlers.ScorableParty {
    }
  }
  

  namespace BowlingGame {
    class Utilities.Score {
    }
  }
  

  namespace BowlingGame {
    class Utilities.ScoreHistoryFile {
    }
  }
  

  namespace BowlingGame {
    class Utilities.ScoreReport {
    }
  }
  

  namespace BowlingGame {
    class Utilities.Util {
    }
  }
  

  namespace BowlingGame {
    namespace Widget {
      class Widget.ButtonPanel {
      }
    }
  }
  

  namespace BowlingGame {
    namespace Widget {
      class Widget.ContainerPanel {
      }
    }
  }
  

  namespace BowlingGame {
    namespace Widget {
      abstract class Widget.FormPanel {
      }
    }
  }
  

  namespace BowlingGame {
    namespace Widget {
      abstract class Widget.GenericPanel {
      }
    }
  }
  

  namespace BowlingGame {
    namespace Widget {
      class Widget.GridPanel {
      }
    }
  }
  

  namespace BowlingGame {
    namespace Widget {
      class Widget.ScrollablePanel {
      }
    }
  }
  

  namespace BowlingGame {
    namespace Widget {
      class Widget.TextFieldPanel {
      }
    }
  }
  

  namespace BowlingGame {
    namespace Widget {
      class Widget.WindowFrame {
      }
    }
  }
  

  ControlDesk.AddPartyView .up.|> java.awt.event.ActionListener
  ControlDesk.AddPartyView .up.|> javax.swing.event.ListSelectionListener
  ControlDesk.AddPartyView o-- Widget.ButtonPanel : buttonPanel
  ControlDesk.AddPartyView o-- ControlDesk.ControlDeskView : controlDesk
  ControlDesk.AddPartyView o-- Widget.WindowFrame : win
  ControlDesk.AdhocView .up.|> java.awt.event.ActionListener
  ControlDesk.AdhocView o-- Widget.ButtonPanel : buttonPanel
  ControlDesk.AdhocView o-- Utilities.Score : currScore
  ControlDesk.AdhocView o-- Widget.ContainerPanel : statDisplay
  ControlDesk.AdhocView o-- Widget.WindowFrame : win
  Bowlers.BowlerScoreView o-- Widget.GridPanel : gridPanel
  ControlDesk.ControlDesk .up.|> java.lang.Runnable
  ControlDesk.ControlDesk -up-|> Observer.Publisher
  Observer.ControlDeskEvent .up.|> Observer.Event
  ControlDesk.ControlDeskView .up.|> Observer.Observer
  ControlDesk.ControlDeskView .up.|> java.awt.event.ActionListener
  ControlDesk.ControlDeskView o-- ControlDesk.ControlDesk : controlDesk
  ControlDesk.ControlDeskView o-- Widget.ButtonPanel : controlsPanel
  ControlDesk.ControlDeskView o-- Widget.WindowFrame : win
  Endgame.EndGamePrompt .up.|> java.awt.event.ActionListener
  Endgame.EndGamePrompt o-- Widget.ButtonPanel : buttonPanel
  Endgame.EndGamePrompt o-- Widget.WindowFrame : win
  Endgame.EndGameReport .up.|> java.awt.event.ActionListener
  Endgame.EndGameReport .up.|> javax.swing.event.ListSelectionListener
  Endgame.EndGameReport o-- Widget.ButtonPanel : buttonPanel
  Endgame.EndGameReport o-- Widget.WindowFrame : win
  Lane.Lane .up.|> LaneInterface
  Lane.Lane .up.|> Observer.Observer
  Lane.Lane .up.|> java.lang.Runnable
  Lane.Lane -up-|> Observer.Publisher
  Lane.Lane o-- Pinsetter.Pinsetter : pinsetter
  Lane.Lane o-- Bowlers.ScorableParty : scorer
  Observer.LaneEvent .up.|> Observer.Event
  Lane.LaneStatusView .up.|> Observer.Observer
  Lane.LaneStatusView .up.|> java.awt.event.ActionListener
  Lane.LaneStatusView o-- Widget.ButtonPanel : buttonPanel
  Lane.LaneStatusView o-- Widget.ContainerPanel : gamePanel
  Lane.LaneStatusView o-- Lane.Lane : lane
  Lane.LaneStatusView o-- Lane.LaneView : laneView
  Lane.LaneStatusView o-- Pinsetter.PinSetterView : pinSetterView
  Lane.LaneView .up.|> Observer.Observer
  Lane.LaneView .up.|> java.awt.event.ActionListener
  Lane.LaneView o-- Widget.ButtonPanel : buttonPanel
  Lane.LaneView o-- Widget.ContainerPanel : containerPanel
  Lane.LaneView o-- LaneInterface : lane
  Bowlers.LastFrame -up-|> Bowlers.Frame
  ControlDesk.NewPatronView .up.|> java.awt.event.ActionListener
  ControlDesk.NewPatronView o-- ControlDesk.AddPartyView : addParty
  ControlDesk.NewPatronView o-- Widget.ButtonPanel : buttonPanel
  ControlDesk.NewPatronView o-- Widget.TextFieldPanel : patronPanel
  ControlDesk.NewPatronView o-- Widget.WindowFrame : window
  Pinsetter.PinSetterView .up.|> Observer.Observer
  Pinsetter.Pinsetter -up-|> Observer.Publisher
  Observer.PinsetterEvent .up.|> Observer.Event
  Utilities.PrintableText .up.|> java.awt.print.Printable
  Bowlers.ScorableBowler -up-|> Bowlers.Bowler
  Bowlers.ScorableParty -up-|> Bowlers.Party
  Widget.ButtonPanel -up-|> Widget.FormPanel
  Widget.ContainerPanel -up-|> Widget.GenericPanel
  Widget.FormPanel -up-|> Widget.GenericPanel
  Widget.GridPanel -up-|> Widget.GenericPanel
  Widget.ScrollablePanel -up-|> Widget.GenericPanel
  Widget.TextFieldPanel -up-|> Widget.FormPanel


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
